apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None 
  selector:
{{ include "db.selectorLabels" . | indent 4 }}
  ports:
  {{- with .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}    
  {{- end }}
  