apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secretsName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "db.labels" . | indent 4 }}
type: Opaque  
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{ end -}}  
