apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "nginx.selectorLabels" . | indent 4 }}
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}