apiVersion: v1
kind: PersistentVolume
metadata:
  name: collected-static-pv
spec:
  capacity:
    storage: 200Mi
  accessModes: 
  - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/collected-static