apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: foodgram
type: Opaque  
data:
  POSTGRES_USER: ZGphbmdvX3VzZXI=
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ=
  POSTGRES_DB: ZGphbmdv
  SECRET_KEY: J2MhbF9AcHMpaTEqc3pxcnh0KmopbGpnaWN2b19uNTViJChya2t1eigtMzY5ZXZiMSF1Jw==
  POSTGRES_REPLICATION_PASSWORD: bXlTdXBlclJlcGxpY2F0aW9uUGFzczEyMyE=

