# nginx-configmap-fixed.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: foodgram
data:
  default.conf: |
    server {
        listen 80;
        client_max_body_size 10M;

        location /api/ {
            proxy_pass http://backend-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /admin/ {
            proxy_pass http://backend-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/admin/ {
            alias /collected-static/admin/;
        }

        location /static/rest_framework/ {
            alias /collected-static/rest_framework/;
        }

        location /static/ {
            root /usr/share/nginx/html;
        }

        location /media/ {
            alias /media/;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }