db:
  secret:
    POSTGRES_USER: ref+vault://secrets/db#/POSTGRES_USER
    POSTGRES_PASSWORD: ref+vault://secrets/db#/POSTGRES_PASSWORD
    POSTGRES_DB: ref+vault://secrets/db#/POSTGRES_DB
    POSTGRES_REPLICATION_PASSWORD: ref+vault://secrets/db#/POSTGRES_REPLICATION_PASSWORD
    POSTGRESQL_REPLICATION_USER: ref+vault://secrets/db#/POSTGRESQL_REPLICATION_USER

backend:
  secret:
    SECRET_KEY: ref+vault://secrets/db#/SECRET_KEY
    apiCocktailDB: ref+vault://secrets/api#/apiCocktailDB
    apiMealDB: ref+vault://secrets/api#/apiMealDB

rabbitmq:  
  secret:
    username: ref+vault://secrets/rabbitmq#/username
    password: ref+vault://secrets/rabbitmq#/password