apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "frontend.fullname" . }}-static-pv
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  {{- with .Values.persistence.static }}
  capacity:
    storage: {{ .size | quote }}
  accessModes: 
  - {{ .accessModes | quote }}
  storageClassName: {{ .storageClassName | quote }}
  hostPath:
    path: {{ .hostPath | quote }}
  {{- end }}