apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | nindent 4 }}
type: Opaque  
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{ end -}}  
