apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "backend.selectorLabels" . | indent 4 }}
  ports:
  {{- with .Values.service.ports }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}