apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{ include "backend.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "backend.selectorLabels" . | indent 8 }}
    spec:
      initContainers:
        - name: static-collector-pod
          {{- with .Values.global.images.api }}
          image: {{ printf "%s:%s" .name .tag }}
          imagePullPolicy: {{ .pullPolicy | quote }}  
          {{- end }}        
          command: {{ .Values.deployment.command | toJson }}
          args: {{ .Values.deployment.args | toJson }}
          env:
            {{- range $key, $val := .Values.deployment.env.value }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $alias, $mapping := .Values.deployment.env.config }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ index $.Values.global.config $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
            {{- range $alias, $mapping := .Values.deployment.env.secret }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.global.secret $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
          command: ["/bin/sh", "-c"]
          args:
          - |
            echo "Running collectstatic and loading ingredients..." &&
            python manage.py collectstatic --noinput &&
            python manage.py load_ingredients --file /app/ingredients.csv --format csv || echo ' Already loaded or skipped'
          volumeMounts:
            - name: {{ .Values.deployment.pvc.static.name }}
              mountPath: {{ .Values.deployment.pvc.static.mountPath }}
      containers:
        - name: backend-pod
          {{- with .Values.global.images.api }}
          image: {{ printf "%s:%s" .name .tag }}
          imagePullPolicy: {{ .pullPolicy | quote }}  
          {{- end }}   
          command: {{ .Values.deployment.command | toJson }}
          args: {{ .Values.deployment.args | toJson }}
          env:
            {{- range $key, $val := .Values.deployment.env.value }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $alias, $mapping := .Values.deployment.env.config }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ index $.Values.global.config $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
            {{- range $alias, $mapping := .Values.deployment.env.secret }}
            {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.global.secret $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.ports }}
      {{- with .Values.deployment.pvc }}
          volumeMounts:  
            - name: {{ .static.name }}
              mountPath: {{ .static.mountPath }}
            - name: {{ .media.name }}
              mountPath: {{ .media.mountPath }}
      volumes:
        - name: {{ .static.name }}
          persistentVolumeClaim:
            claimName: {{ include "backend.fullname" $ }}-collected-pvc
        - name: {{ .media.name }}       
          persistentVolumeClaim:
            claimName: {{ include "backend.fullname" $ }}-media-pvc        
      {{- end }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable }}
 