apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend.fullname" . }}-media-pvc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  {{- with .Values.persistence.media }}
  accessModes: 
  - {{ .accessModes | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
  storageClassName: {{ .storageClassName | quote }}  
  {{- end }}
  volumeName: {{ include "backend.fullname" . }}-media-pv
