apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "rabbitmq.labels" . | indent 4 }}
data:
  host: rabbitmq-foodgram.foodgram.svc.cluster.local
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{ end -}}  