apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "db.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{ end -}}
